### ISSUE TITLE
Check throws when the token is not castable to uniqueidentifier

### ISSUE THREAD

**Issue by IsaacSee** [Invenietis/CK-DB-TokenStore#1]
During the check, the token is hard-casted to a uniqueidentifier here:
https://github.com/Invenietis/CK-DB-TokenStore/blob/68a906642e4b86bac0b899176c33a9380addaf03/CK.DB.TokenStore/Res/sTokenCheck.sql#L18

Would it make sense to just keep it silent and consider it a failed check ?
It could simply be done replacing the cast by a try_cast and go directly to the OnTokenMissing if the _try_casted_ token is null.

**Comment by olivier-spinelli** [comment]
Good catch: yes a "syntactically invalid" should behave the same as a "simply invalid" one.

**Comment by milleniu** [comment]
Changes were pushed in the referenced commit. This will be released alongside the next stack release. However, until then, you may use the last CI version 0.2.1--0009-develop.

It should be noted this CI build also includes other changes:

- TokenKey and TokenScope now define their collation in the TokenStoreTable model.
- The --<AdditionalSecurity /> artifact in the sTokenCheck procedure has been updated and now uses of an IsValid bit.

**Comment by IsaacSee** [comment]
Great ! Thank you !
